# Generated by Django 4.0 on 2022-01-17 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usersapp", "0003_alter_user_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("uuid", models.UUIDField(default=4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("repository", models.URLField(blank=True)),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ToDo",
            fields=[
                ("uuid", models.UUIDField(default=4, primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("create", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="usersapp.user")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="todoapp.project")),
            ],
        ),
    ]
