# Generated by Django 4.0 on 2022-01-02 17:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fab484b7-a9af-4acc-bbe7-f73bc40f035e"), primary_key=True, serialize=False
            ),
        ),
    ]
