# Generated by Django 4.0 on 2022-01-17 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_user_birthday_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef96e95a-adab-4226-9154-00ca6a51b567'), primary_key=True, serialize=False),
        ),
    ]
