# Generated by Django 4.0 on 2022-01-17 21:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("584de665-adc4-4467-aa4f-5c0b3f0bc110"), primary_key=True, serialize=False
            ),
        ),
    ]
