# Generated by Django 4.0 on 2022-01-17 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('72505c03-8966-4e6c-8177-62df50d9ae1c'), primary_key=True, serialize=False),
        ),
    ]
