# Generated by Django 4.0 on 2022-01-19 23:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersapp", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
